USE [Inventario]
GO
/****** Object:  StoredProcedure [dbo].[SP_Cart_Select_ByName]    Script Date: 21/4/2025 9:44:52 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_Cart_Select_ByName]
@Name VARCHAR(55) = NULL
AS
SET NOCOUNT ON;
BEGIN
	BEGIN TRY
		BEGIN
			SELECT * FROM dbo.Cart WHERE Name = @Name
		END
	END TRY
		BEGIN CATCH
			SELECT ERROR_MESSAGE() AS ERROR,
				ERROR_NUMBER() AS ERROR_NRO
		END CATCH;
END